# Generated by Django 2.1.7 on 2019-08-18 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.CharField(max_length=10)),
                ('session', models.CharField(max_length=36)),
                ('level', models.CharField(max_length=10)),
                ('action', models.IntegerField()),
                ('time', models.FloatField()),
                ('state', models.TextField()),
            ],
        ),
    ]
